apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shipping-service.configMapName" . }}
  namespace: {{ required "global.namespace es obligatorio" .Values.global.namespace | quote }}
  labels:
    {{- include "shipping-service.labels" . | nindent 4 }}
data:
  SERVICE_NAME: {{ .Values.config.serviceName | quote }}
  LOG_LEVEL: {{ default "info" .Values.global.logLevel | quote }}
  RABBITMQ_HOST: {{ .Values.config.rabbitmqHost | quote }}
  RABBITMQ_PORT: {{ .Values.config.rabbitmqPort | quote }}
  RABBITMQ_QUEUE: {{ .Values.config.rabbitmqQueue | quote }}
