global:
  namespace: sa-p8-dev
  environment: dev
  logLevel: debug
  imageTag: "1.1.4"
catalog-service:
  replicaCount: 2
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 128Mi

inventory-service:
  replicaCount: 2
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 128Mi

orders-service:
  replicaCount: 2
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 128Mi

shipping-service:
  replicaCount: 2
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 128Mi

auth-service:
  replicaCount: 2
  resources:
    requests:
      cpu: 100m
      memory: 96Mi
    limits:
      cpu: 300m
      memory: 192Mi

gateway:
  replicaCount: 2
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 128Mi
