{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-authorized-to-postgresql
  namespace: {{ .Values.global.namespace | quote }}
  labels:
    {{- include "sa-platform.labels" . | nindent 4 }}

spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: primary

  policyTypes:
    - Ingress

  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: "auth-service"
              app.kubernetes.io/instance: {{ .Release.Name | quote }}

        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ .Values.networkPolicy.futureCronJobs.databaseWriter | quote }}

        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ .Values.networkPolicy.futureCronJobs.summaryPublisher | quote }}

      ports:
        - protocol: TCP
          port: 5432
{{- end }}
