apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "catalog-service.configMapName" . }}
  namespace: {{ required "global.namespace es obligatorio" .Values.global.namespace | quote }}
  labels:
    {{- include "catalog-service.labels" . | nindent 4 }}
data:
  SERVICE_NAME: {{ .Values.config.serviceName | quote }}
  LOG_LEVEL: {{ default "info" .Values.global.logLevel | quote }}
