apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "catalog-service.fullname" . }}
  namespace: {{ .Values.global.namespace | quote }}
  labels:
    {{- include "catalog-service.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    canary:
      steps:
        - setWeight: 20
        - analysis:
            templates:
              - templateName: {{ include "catalog-service.fullname" . }}-analysis
        - setWeight: 50
        - analysis:
            templates:
              - templateName: {{ include "catalog-service.fullname" . }}-analysis
        - setWeight: 80
        - analysis:
            templates:
              - templateName: {{ include "catalog-service.fullname" . }}-analysis

  selector:
    matchLabels:
      {{- include "catalog-service.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "catalog-service.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}

    spec:
      serviceAccountName: {{ .Values.serviceAccount.name | quote }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automount }}

      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      containers:
        - name: catalog-service

          image: "{{ .Values.image.repository }}:{{ default .Values.global.imageTag .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP

          envFrom:
            - configMapRef:
                name: {{ include "catalog-service.configMapName" . }}

          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          startupProbe:
            httpGet:
              path: {{ .Values.probes.startup.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.startup.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.startup.periodSeconds }}
            failureThreshold: {{ .Values.probes.startup.failureThreshold }}

          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}

          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
