apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ include "inventory-service.fullname" . }}-analysis
  namespace: {{ .Values.global.namespace | quote }}
  labels:
    {{- include "inventory-service.labels" . | nindent 4 }}
spec:
  metrics:
    - name: health-check
      interval: 10s
      count: 3
      successCondition: "result == 'ok'"
      failureLimit: 1
      provider:
        web:
          url: "http://{{ .Values.config.serviceName }}.{{ .Values.global.namespace }}.svc.cluster.local:{{ .Values.service.port }}/health"
          timeoutSeconds: 5
          jsonPath: "{$.status}"
