apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "auth-service.configMapName" . }}
  namespace: {{ required "global.namespace es obligatorio" .Values.global.namespace | quote }}
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
data:
  SERVICE_NAME: {{ .Values.config.serviceName | quote }}
  LOG_LEVEL: {{ default "info" .Values.global.logLevel | quote }}
  PORT: {{ .Values.config.port | quote }}
  FRONTEND_URL: {{ .Values.config.frontendUrl | quote }}
  JWT_EXPIRES_IN_SECONDS: {{ .Values.config.jwtExpiresInSeconds | quote }}
  JWT_REFRESH_GRACE_SECONDS: {{ .Values.config.jwtRefreshGraceSeconds | quote }}
