apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: p8-platform-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://github.com/Noe94/SA-P8-GitOps-201700866.git
    targetRevision: main
    path: charts/sa-platform
    helm:
      releaseName: sa-platform
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: sa-p8-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
