apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: p8-policies
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: default

  source:
    repoURL: https://github.com/Noe94/SA-P8-GitOps-201700866.git
    targetRevision: main
    path: policies

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
